INSERT INTO Products (name, description, price) VALUES('Celular', 'Motorola G6 Play', 700.00);
INSERT INTO Products (name, description, price) VALUES('Celular', 'Motorola G10', 1700.00);
INSERT INTO Products (name, description, price) VALUES('Celular', 'Motorola G8', 999.00);
INSERT INTO Products (name, description, price) VALUES('Celular', 'Samsung A50', 890.00);
INSERT INTO Products (name, description, price) VALUES('Celular', 'Iphone 11', 4800.00);
INSERT INTO Products (name, description, price) VALUES('Celular', 'Iphone 10C', 1900.00);
INSERT INTO Products (name, description, price) VALUES('Tablet', 'Motorola Zoom', 800.00);
INSERT INTO Products (name, description, price) VALUES('Tablet', 'Samsung Galaxy Note', 2200.00);
INSERT INTO Products (name, description, price) VALUES('Tablet', 'Ipad 5', 2700.00);
INSERT INTO Products (name, description, price) VALUES('Celular', 'LG Z30', 900.00);
